# Generated by Django 4.0.8 on 2022-12-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=17)),
                ('start_time', models.DateTimeField()),
                ('usage_time', models.DurationField()),
                ('upload', models.PositiveIntegerField()),
                ('download', models.PositiveIntegerField()),
            ],
        ),
    ]
