# Generated by Django 4.0.8 on 2022-12-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0002_rename_user_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
